// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mask_gen_reg_pkg;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////
  typedef struct packed {
    struct packed {
      logic [4:0]  q;
    } pattern_w;
    struct packed {
      logic        q;
    } pattern;
    struct packed {
      logic [7:0]  q;
    } repeatedpattern;
    struct packed {
      logic        q;
    } load_pattern;
    struct packed {
      logic [1:0]  q;
    } mask_type;
    struct packed {
      logic        q;
    } next;
    struct packed {
      logic [1:0]  q;
    } imgres;
  } mask_gen_reg2hw_mod_in_reg_t;


  typedef struct packed {
    logic [19:0] d;
    logic        de;
  } mask_gen_hw2reg_mod_out_reg_t;


  ///////////////////////////////////////
  // Register to internal design logic //
  ///////////////////////////////////////
  typedef struct packed {
    mask_gen_reg2hw_mod_in_reg_t mod_in; // [20:1]
  } mask_gen_reg2hw_t;

  ///////////////////////////////////////
  // Internal design logic to register //
  ///////////////////////////////////////
  typedef struct packed {
    mask_gen_hw2reg_mod_out_reg_t mod_out; // [21:22]
  } mask_gen_hw2reg_t;

  // Register Address
  parameter logic [2:0] MASK_GEN_MOD_OUT_OFFSET = 3'h 0;
  parameter logic [2:0] MASK_GEN_MOD_IN_OFFSET = 3'h 4;


  // Register Index
  typedef enum int {
    MASK_GEN_MOD_OUT,
    MASK_GEN_MOD_IN
  } mask_gen_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MASK_GEN_PERMIT [2] = '{
    4'b 0111, // index[0] MASK_GEN_MOD_OUT
    4'b 0111  // index[1] MASK_GEN_MOD_IN
  };
endpackage

