// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module mask_gen_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic
) (
  input clk_i,
  input rst_ni,

  // Below Register interface can be changed
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output mask_gen_reg_pkg::mask_gen_reg2hw_t reg2hw, // Write
  input  mask_gen_reg_pkg::mask_gen_hw2reg_t hw2reg, // Read

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import mask_gen_reg_pkg::* ;

  localparam int AW = 3;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;

  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err ;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [19:0] mod_out_qs;
  logic [19:0] mod_out_wd;
  logic mod_out_we;
  logic mod_out_re;
  logic [4:0] mod_in_pattern_w_qs;
  logic [4:0] mod_in_pattern_w_wd;
  logic mod_in_pattern_w_we;
  logic mod_in_pattern_qs;
  logic mod_in_pattern_wd;
  logic mod_in_pattern_we;
  logic [7:0] mod_in_repeatedpattern_qs;
  logic [7:0] mod_in_repeatedpattern_wd;
  logic mod_in_repeatedpattern_we;
  logic mod_in_load_pattern_qs;
  logic mod_in_load_pattern_wd;
  logic mod_in_load_pattern_we;
  logic [1:0] mod_in_mask_type_qs;
  logic [1:0] mod_in_mask_type_wd;
  logic mod_in_mask_type_we;
  logic mod_in_next_qs;
  logic mod_in_next_wd;
  logic mod_in_next_we;
  logic [1:0] mod_in_imgres_qs;
  logic [1:0] mod_in_imgres_wd;
  logic mod_in_imgres_we;

  // Register instances
  // R[mod_out]: V(True)

  prim_subreg_ext #(
    .DW    (20)
  ) u_mod_out (
    .re     (mod_out_re),
    .we     (mod_out_we),
    .wd     (mod_out_wd),
    .d      (hw2reg.mod_out.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (mod_out_qs)
  );


  // R[mod_in]: V(False)

  //   F[pattern_w]: 4:0
  prim_subreg #(
    .DW      (5),
    .SWACCESS("RW"),
    .RESVAL  (5'h0)
  ) u_mod_in_pattern_w (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_pattern_w_we),
    .wd     (mod_in_pattern_w_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.pattern_w.q ),

    // to register interface (read)
    .qs     (mod_in_pattern_w_qs)
  );


  //   F[pattern]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_mod_in_pattern (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_pattern_we),
    .wd     (mod_in_pattern_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.pattern.q ),

    // to register interface (read)
    .qs     (mod_in_pattern_qs)
  );


  //   F[repeatedpattern]: 13:6
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_mod_in_repeatedpattern (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_repeatedpattern_we),
    .wd     (mod_in_repeatedpattern_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.repeatedpattern.q ),

    // to register interface (read)
    .qs     (mod_in_repeatedpattern_qs)
  );


  //   F[load_pattern]: 14:14
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_mod_in_load_pattern (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_load_pattern_we),
    .wd     (mod_in_load_pattern_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.load_pattern.q ),

    // to register interface (read)
    .qs     (mod_in_load_pattern_qs)
  );


  //   F[mask_type]: 16:15
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_mod_in_mask_type (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_mask_type_we),
    .wd     (mod_in_mask_type_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.mask_type.q ),

    // to register interface (read)
    .qs     (mod_in_mask_type_qs)
  );


  //   F[next]: 17:17
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_mod_in_next (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_next_we),
    .wd     (mod_in_next_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.next.q ),

    // to register interface (read)
    .qs     (mod_in_next_qs)
  );


  //   F[imgres]: 19:18
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_mod_in_imgres (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mod_in_imgres_we),
    .wd     (mod_in_imgres_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mod_in.imgres.q ),

    // to register interface (read)
    .qs     (mod_in_imgres_qs)
  );




  logic [1:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == MASK_GEN_MOD_OUT_OFFSET);
    addr_hit[1] = (reg_addr == MASK_GEN_MOD_IN_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 1'b0;
    if (addr_hit[0] && reg_we && (MASK_GEN_PERMIT[0] != (MASK_GEN_PERMIT[0] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[1] && reg_we && (MASK_GEN_PERMIT[1] != (MASK_GEN_PERMIT[1] & reg_be))) wr_err = 1'b1 ;
  end

  assign mod_out_we = addr_hit[0] & reg_we & ~wr_err;
  assign mod_out_wd = reg_wdata[19:0];
  assign mod_out_re = addr_hit[0] && reg_re;

  assign mod_in_pattern_w_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_pattern_w_wd = reg_wdata[4:0];

  assign mod_in_pattern_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_pattern_wd = reg_wdata[5];

  assign mod_in_repeatedpattern_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_repeatedpattern_wd = reg_wdata[13:6];

  assign mod_in_load_pattern_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_load_pattern_wd = reg_wdata[14];

  assign mod_in_mask_type_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_mask_type_wd = reg_wdata[16:15];

  assign mod_in_next_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_next_wd = reg_wdata[17];

  assign mod_in_imgres_we = addr_hit[1] & reg_we & ~wr_err;
  assign mod_in_imgres_wd = reg_wdata[19:18];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[19:0] = mod_out_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[4:0] = mod_in_pattern_w_qs;
        reg_rdata_next[5] = mod_in_pattern_qs;
        reg_rdata_next[13:6] = mod_in_repeatedpattern_qs;
        reg_rdata_next[14] = mod_in_load_pattern_qs;
        reg_rdata_next[16:15] = mod_in_mask_type_qs;
        reg_rdata_next[17] = mod_in_next_qs;
        reg_rdata_next[19:18] = mod_in_imgres_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))


endmodule
