// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mask_gen_reg_pkg;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////
  typedef struct packed {
    logic [19:0] q;
  } mask_gen_reg2hw_output_reg_t;

  typedef struct packed {
    struct packed {
      logic [4:0]  q;
    } pattern_w;
    struct packed {
      logic        q;
    } pattern;
    struct packed {
      logic [7:0]  q;
    } repeatedpattern;
    struct packed {
      logic        q;
    } load_pattern;
    struct packed {
      logic [1:0]  q;
    } mask_type;
    struct packed {
      logic        q;
    } next;
    struct packed {
      logic [1:0]  q;
    } imgres;
  } mask_gen_reg2hw_input_reg_t;



  ///////////////////////////////////////
  // Register to internal design logic //
  ///////////////////////////////////////
  typedef struct packed {
    mask_gen_reg2hw_output_reg_t output; // [40:21]
    mask_gen_reg2hw_input_reg_t input; // [20:1]
  } mask_gen_reg2hw_t;

  ///////////////////////////////////////
  // Internal design logic to register //
  ///////////////////////////////////////

  // Register Address
  parameter logic [2:0] MASK_GEN_OUTPUT_OFFSET = 3'h 0;
  parameter logic [2:0] MASK_GEN_INPUT_OFFSET = 3'h 4;


  // Register Index
  typedef enum int {
    MASK_GEN_OUTPUT,
    MASK_GEN_INPUT
  } mask_gen_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MASK_GEN_PERMIT [2] = '{
    4'b 0111, // index[0] MASK_GEN_OUTPUT
    4'b 0111  // index[1] MASK_GEN_INPUT
  };
endpackage

